// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpNay4bxRVXAdNjdEMDaTojjxDMD_vnBM',
    appId: '1:935842442770:web:c44da12fce56d5486eb2cb',
    messagingSenderId: '935842442770',
    projectId: 'chat-gaurav-df9b0',
    authDomain: 'chat-gaurav-df9b0.firebaseapp.com',
    storageBucket: 'chat-gaurav-df9b0.appspot.com',
    measurementId: 'G-68DREVBV3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxsWkhvyxjPIWQ4j525Vf8z4Pej4GYx4w',
    appId: '1:935842442770:android:a5b0676eae05a8b36eb2cb',
    messagingSenderId: '935842442770',
    projectId: 'chat-gaurav-df9b0',
    storageBucket: 'chat-gaurav-df9b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSr9Wx-uR5S3mQPkQr7JYH3Y1GE2stN5g',
    appId: '1:935842442770:ios:6770e1dc5dabccad6eb2cb',
    messagingSenderId: '935842442770',
    projectId: 'chat-gaurav-df9b0',
    storageBucket: 'chat-gaurav-df9b0.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSr9Wx-uR5S3mQPkQr7JYH3Y1GE2stN5g',
    appId: '1:935842442770:ios:5f304c2557b935bc6eb2cb',
    messagingSenderId: '935842442770',
    projectId: 'chat-gaurav-df9b0',
    storageBucket: 'chat-gaurav-df9b0.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
